services:
  app:
    build: .
    image: user-service-api
    # image: samarthya2301/user-service-api:latest
    container_name: user-service-api
    ports:
      - "3001:8080"
    volumes:
      - ~/.aws:/root/.aws:ro
    environment:
      SECRETS_JWT_KEY: ${SECRETS_JWT_KEY}
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/expense_intelligence
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: expense_intelligence
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
