version: "3.9"

services:
  app:
    image: user-service-api
    ports:
      - "3001:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/expense_intelligence
      SPRING_DATASOURCE_USERNAME: 'dev'
      SPRING_DATASOURCE_PASSWORD: 'dev'
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: expense_intelligence
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'dev'
