controller:
  paths:
    check-and-test:
      health-check: /healthCheck
      test-auth: /test-auth
    login:
      login: /login
      refresh-token: /refresh-token
    otp:
      otp-request: /otp/request
      otp-verify: /otp/verify
    register:
      register: /register

service:
  otp:
    expire-after-seconds: 300
  token:
    jwt:
      claim:
        key:
          user-id: user_id
          user-email: user_email
          user-role: user_role
      expire-after-seconds: 86400
    refresh:
      expire-after-seconds: 604800

logging:
  level:
    root: INFO
    '[com.samarthya_dev.user_service]': DEBUG

secrets:
  jwt:
    key: ${SECRETS_JWT_KEY}

server:
  port: 3001

spring:
  config:
    import: "optional:file:.env[.properties]"
  profiles:
    active: dev
