controller:
  paths:
    check-and-test:
      health-check: /healthCheck
      test-auth: /test-auth
    login:
      login: /login
      refresh-token: /refresh
    otp:
      otp-request: /otp/request
      otp-verify: /otp/verify
    register:
      register: /register


logging:
  level:
    root: INFO
    '[com.samarthya_dev.user_service]': DEBUG

secrets:
  jwt:
    key: ${SECRETS_JWT_KEY}

server:
  port: 3001

spring:
  config:
    import: "optional:file:.env[.properties]"
  profiles:
    active: dev
