server:
  port: 3001

spring:
  config:
    import: "optional:file:.env[.properties]"
  profiles:
    active: dev

logging:
  level:
    root: INFO
    '[com.samarthya_dev.user_service]': DEBUG

secrets:
  jwt:
    key: ${SECRETS_JWT_KEY}