name: CI

# define when to invoke jobs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# all jobs to invoke
jobs:

  # job 1: build with maven and upload artifact for 'docker-build-and-push'
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build Artifact with Maven
        run: mvn clean verify

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  # job 2: download artifact from 'maven-build', build docker image and push to docker hub
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: target/
      
      - name: Log In to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Image with Docker
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/user-service-api
          TAG=${{ github.sha }}
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .
      
      - name: Push Image to Docker Hub
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/user-service-api
          TAG=${{ github.sha }}
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
